# Generated by Django 3.2 on 2021-10-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('place', models.CharField(max_length=50)),
                ('stipend', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=5)),
                ('eligibility', models.CharField(max_length=600)),
                ('prereq', models.CharField(max_length=400)),
                ('deliverables', models.CharField(max_length=400)),
                ('duration', models.CharField(max_length=50)),
                ('wishlist', models.BooleanField(default=False)),
            ],
        ),
    ]
