# Generated by Django 2.2.5 on 2021-11-01 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_auto_20211101_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_1', models.IntegerField(blank=True, null=True)),
                ('pref_2', models.IntegerField(blank=True, null=True)),
                ('pref_3', models.IntegerField(blank=True, null=True)),
                ('pref_4', models.IntegerField(blank=True, null=True)),
                ('pref_5', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
